### ISSUE TITLE
Unrecoverable error 

### ISSUE THREAD

**Issue by williampincek47** [Juniper/terraform-provider-apstra#690] opened 2024-06-28 15:31 UTC
Hi,

I understand that I should not do this.  I just happened to accidentally perform the following, and at a minimum, it broke the Staged > Virtual > Routing Zones UI page (may have caused other unknown problems but not sure)....

I accidentally created a configuration that allocates IPv4 resource pools to allocation groups that do not exist in a routing zone (Finance in my config).  I was able to successfully apply the configuration with no errors from Terraform.  Then, using the UI to navigate to Staged > Virtual > Routing Zones, I noticed the page was completely blank.  Then, I used Terraform to destroy the apstra_datacenter_resource_pool_allocation resource that caused the problem but the Routing Zones page remained blank in the UI.  I had to restore my Apstra server to a previous backup and start all over with Terraform to recover.

I've attached the blueprint.tf file that caused the problem.  There are local variables defined to help in the allocation on lines 31-34.  The apstra_datacenter_resource_pool_allocation resource that caused the problem is on lines 221-227.

Hope that helps,

Will Pincek
[bad-blueprint.txt](https://github.com/user-attachments/files/16032840/bad-blueprint.txt)

**Comment by chrismarget-j** [comment] 2024-06-28 15:37
Hey Will,

This is a known issue in Apstra: AOS-42106 (September of ’23)

Unfortunately, I don’t think there’s anything we can do to defend against it in terraform.

/chris



Juniper Business Use Only
From: williampincek47 ***@***.***>
Date: Friday, June 28, 2024 at 11:31 AM
To: Juniper/terraform-provider-apstra ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Juniper/terraform-provider-apstra] Unrecoverable error (Issue #690)
[External Email. Be cautious of content]


Hi,

I understand that I should not do this. I just happened to accidentally perform the following, and at a minimum, it broke the Staged > Virtual > Routing Zones UI page (may have caused other unknown problems but not sure)....

I accidentally created a configuration that allocates IPv4 resource pools to allocation groups that do not exist in a routing zone (Finance in my config). I was able to successfully apply the configuration with no errors from Terraform. Then, using the UI to navigate to Staged > Virtual > Routing Zones, I noticed the page was completely blank. Then, I used Terraform to destroy the apstra_datacenter_resource_pool_allocation resource that caused the problem but the Routing Zones page remained blank in the UI. I had to restore my Apstra server to a previous backup and start all over with Terraform to recover.

I've attached the blueprint.tf file that caused the problem. There are local variables defined to help in the allocation on lines 31-34. The apstra_datacenter_resource_pool_allocation resource that caused the problem is on lines 221-227.

Hope that helps,

Will Pincek
bad-blueprint.txt<https://urldefense.com/v3/__https:/github.com/user-attachments/files/16032840/bad-blueprint.txt__;!!NEt6yMaO-gk!CDO2D2RWDkswry61BpyN4thxmjTJahVZZOPn033Rsz4W1VmWZEYvN9Ajg2-EeLCorbx6E0qL-ZLFur9t5ajrSXE_$>

**Comment by williampincek47** [comment] 2024-06-28 16:52
Ok cool. No problem.

Thanks for looking at it.

Will Pincek

On Jun 28, 2024, at 11:37 AM, chrismarget-j ***@***.***> wrote:

﻿

Hey Will,

This is a known issue in Apstra: AOS-42106 (September of ’23)

Unfortunately, I don’t think there’s anything we can do to defend against it in terraform.

/chris



Juniper Business Use Only
From: williampincek47 ***@***.***>
Date: Friday, June 28, 2024 at 11:31 AM
To: Juniper/terraform-provider-apstra ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Juniper/terraform-provider-apstra] Unrecoverable error (Issue #690)
[External Email. Be cautious of content]


Hi,

I understand that I should not do this. I just happened to accidentally perform the following, and at a minimum, it broke the Staged > Virtual > Routing Zones UI page (may have caused other unknown problems but not sure)....

I accidentally created a configuration that allocates IPv4 resource pools to allocation groups that do not exist in a routing zone (Finance in my config). I was able to successfully apply the configuration with no errors from Terraform. Then, using the UI to navigate to Staged > Virtual > Routing Zones, I noticed the page was completely blank. Then, I used Terraform to destroy the apstra_datacenter_resource_pool_allocation resource that caused the problem but the Routing Zones page remained blank in the UI. I had to restore my Apstra server to a previous backup and start all over with Terraform to recover.

I've attached the blueprint.tf file that caused the problem. There are local variables defined to help in the allocation on lines 31-34. The apstra_datacenter_resource_pool_allocation resource that caused the problem is on lines 221-227.

Hope that helps,

Will Pincek
bad-blueprint.txt<https://urldefense.com/v3/__https:/github.com/user-attachments/files/16032840/bad-blueprint.txt__;!!NEt6yMaO-gk!CDO2D2RWDkswry61BpyN4thxmjTJahVZZOPn033Rsz4W1VmWZEYvN9Ajg2-EeLCorbx6E0qL-ZLFur9t5ajrSXE_$>

**Comment by chrismarget-j** [comment] 2024-07-12 01:43
AOS-42106 work is in progress. Fixes will be there. Closing this issue for now.

**Closed by chrismarget-j** 2024-07-12 01:43 UTC
