### ISSUE TITLE
Error: Incorrect attribute value type after trying create link with freeform link module

### ISSUE THREAD

**Issue by ihadi581** [Juniper/terraform-provider-apstra#795] opened 2024-08-17 05:00 UTC
this exmaple tf file:
```
resource "apstra_freeform_link" "sp1_lf1" {
  blueprint_id = apstra_freeform_blueprint.dc1.id
  name         = "sp1_lf1"
  tags         = null
  endpoints    = [
            {     
            system_id         = "4WBxH-fmNj1Q2eTr3aI" 
            interface_name    = "ge-0/0/0"
            ipv4_address      = "192.168.1.1/30"
            transformation_id = 1
            },
            {     
            system_id         = "TGSCjWX7SloVcAacyCQ"
            interface_name    = "ge-0/0/0"
            ipv4_address      = "192.168.1.2/30"
            transformation_id = 1
            }
      ]
}
```
this output running terraform:
```
terraform plan
╷
│ Error: Incorrect attribute value type
│ 
│   on dc1-infra.tf line 429, in resource "apstra_freeform_link" "sp1_lf1":
│  429:   endpoints    = [
│  430:             {     
│  431:             system_id         = "4WBxH-fmNj1Q2eTr3aI" 
│  432:             interface_name    = "ge-0/0/0"
│  433:             ipv4_address      = "192.168.1.1/30"
│  434:             transformation_id = 1
│  435:             },
│  436:             {     
│  437:             system_id         = "TGSCjWX7SloVcAacyCQ"
│  438:             interface_name    = "ge-0/0/0"
│  439:             ipv4_address      = "192.168.1.2/30"
│  440:             transformation_id = 1
│  441:             }
│  442:       ]
│ 
│ Inappropriate value for attribute "endpoints": map of object required.
╵
```

**Comment by chrismarget-j** [comment] 2024-08-18 02:41
yep, this is a documentation bug.

The `endpoints` attribute is a map keyed by system ID. So, in this case, it should look more like:

```terraform
  endpoints    = {
           4WBxH-fmNj1Q2eTr3aI =  {     
            interface_name    = "ge-0/0/0"
            ipv4_address      = "192.168.1.1/30"
            transformation_id = 1
            },
            TGSCjWX7SloVcAacyCQ = {     
            interface_name    = "ge-0/0/0"
            ipv4_address      = "192.168.1.2/30"
            transformation_id = 1
            }
      }
```

**Comment by chrismarget-j** [comment] 2024-08-18 04:01
Duplicate of #791

**Closed by chrismarget-j** 2024-08-18 04:01 UTC
